### ISSUE TITLE
design article page wireframe

### ISSUE THREAD

**Issue by muubar** [chingu-voyage4/Bears-Team-5#4]

**Comment by CZweers** [comment]
https://wireframe.cc/pro/pp/62ba3236e145502

**Comment by CZweers** [comment]
like so?

**Comment by CZweers** [comment]
new version: https://wireframe.cc/pro/pp/62ba3236e145502

**Comment by CZweers** [comment]
newest: https://wireframe.cc/pro/pp/62ba3236e145502
